//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexGains.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> WorkoutId { get; set; }
        public Nullable<System.DateTime> CommentDateTime { get; set; }
        public string TextBody { get; set; }
    
        public virtual Workout Workout { get; set; }
        public virtual Account Account { get; set; }
    }
}
