//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexGains.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutStep
    {
        public int StepId { get; set; }
        public Nullable<int> WorkoutId { get; set; }
        public Nullable<int> ExerciseId { get; set; }
        public Nullable<byte> WorkoutOrder { get; set; }
        public Nullable<int> RepsNumber { get; set; }
        public Nullable<int> SetsNumber { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
